language: go

dist: xenial
os: linux

go:
    - 1.13.5
    - 1.12
    - 1.11.x
    - master

before_script:
    - go get -u golang.org/x/lint/golint

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - golint ./...
    - go build ./cmd/gorkin
    - go test ./lexer
    - go test ./parser
