language: go

dist: xenial
os: linux

go:
    - stable
    - 1.16
    - 1.15
    - 1.14
    - 1.13

before_script:
    - go get -u golang.org/x/lint/golint

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - golint ./...
    - go build ./cmd/gorkin
    - go test ./filter -v
    - go test ./lexer -v
    - go test ./object -v
    - go test ./parser -v
